dist: xenial
language: cpp
compiler: gcc

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - cmake

script:
    - ./install_dependencies.sh
    - ./autobuild.sh
